apiVersion: v1
kind: Service
metadata:
  name: coll-47093d9c7c8a42cd8509ae8efd3b1846-srv
spec:
  selector:
    app: coll-47093d9c7c8a42cd8509ae8efd3b1846
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP